export let GET_PRODUCT_SUCCESS = "GET_PRODUCT_SUCCESS"
export let GET_PRODUCT_PENDING = "GET_PRODUCT_PENDING"
export let GET_PRODUCT_NOTFOUND = "GET_PRODUCT_NOTFOUND"


export let POST_PRODUCT_SUCCESS = "POST_PRODUCT_SUCCESS"
export let POST_PRODUCT_PENDING = "POST_PRODUCT_PENDING"
export let POST_PRODUCT_NOTFOUND = "POST_PRODUCT_NOTFOUND"

export let DELETE_PRODUCT_SUCCESS = "DELETE_PRODUCT_SUCCESS"
export let DELETE_PRODUCT_PENDING = "DELETE_PRODUCT_PENDING"
export let DELETE_PRODUCT_NOTFOUND = "DELETE_PRODUCT_NOTFOUND"